### ISSUE TITLE
<content> tag with no closing tag in index.html

### ISSUE THREAD

**Issue by tif-calin** [dpcairns/alchemy-bootstrap-template#2]
in the middle of the `<body>` in index.html, there's a lone `<content>` tag with no closing tag. According to MDN, the `<content>` is obsolete HTML and should not be used 

:P

**Comment by tif-calin** [comment]
Actually I realized there's a CSS selector for `content` so it'd be a better call to add a closing tag instead

Also in styles.css, the @keyframes selector is indented which makes everything a user adds after it indented as well

**Comment by dpcairns** [comment]
nice, thanks!
